In [1]:
import numpy as np

In [2]:
np.__version__


'2.3.2'

# Create & Read ¶

#### 1D Array

In [3]:
arr1 = np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr1.shape

(6,)

In [6]:
arr1.dtype

dtype('int64')

In [7]:
arr1.ndim


1

In [8]:
arr1.size

6

## 2D Array

In [9]:
arr2= np.array([[1,4,5],[6,7,4]])
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [10]:
arr2.ndim

2

In [11]:
arr2.shape

(2, 3)

In [12]:
arr2.size

6

## 3D Array

In [13]:
arr3= np.array([[[1,4,5],[6,7,4]], [[3,5,4], [5,8,7]], [[1,4,5],[6,7,4]] ])
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [14]:
arr3.ndim

3

In [15]:
arr3.shape

(3, 2, 3)

In [16]:
arr3.size


18

## Create Random Array

In [17]:
randomArr= np.random.rand(3,2,3)
randomArr

array([[[0.32350259, 0.93586333, 0.66433834],
        [0.590175  , 0.60053216, 0.87874712]],

       [[0.78495525, 0.76598906, 0.7145403 ],
        [0.59507046, 0.25720581, 0.26371906]],

       [[0.31694665, 0.52004789, 0.86595119],
        [0.80901297, 0.75534302, 0.01198061]]])

In [18]:
randomArr.dtype

dtype('float64')

In [19]:
zeroes= np.zeros((3,2,3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [20]:
zeroes.ndim

3

In [21]:
full= np.full((3,2,3),9)
full

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

In [22]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [23]:
arr3[0:1]

array([[[1, 4, 5],
        [6, 7, 4]]])

In [24]:
arr3[-2]

array([[3, 5, 4],
       [5, 8, 7]])

In [25]:
arr3[1][0][1]

np.int64(5)

In [26]:
arr3[1,0,1]

np.int64(5)

#### Update and Delete

In [27]:
a1= np.random.rand(2,3,2)
a2= np.random.rand(2,3,2)

In [28]:
a1

array([[[0.53775878, 0.21183937],
        [0.11720024, 0.32617217],
        [0.54260664, 0.39440351]],

       [[0.08888738, 0.1822183 ],
        [0.27946473, 0.91062054],
        [0.9905615 , 0.92124989]]])

In [29]:
a2

array([[[0.39731896, 0.17370182],
        [0.40817891, 0.42764775],
        [0.30642908, 0.56916559]],

       [[0.00380269, 0.55076564],
        [0.02954208, 0.81219192],
        [0.39382812, 0.11379462]]])

## Basic Math Operation

In [30]:
np.add(a1,a2)

array([[[0.93507774, 0.38554119],
        [0.52537916, 0.75381992],
        [0.84903572, 0.9635691 ]],

       [[0.09269007, 0.73298395],
        [0.30900681, 1.72281245],
        [1.38438963, 1.0350445 ]]])

In [31]:
np.subtract(a1,a2)

array([[[ 0.14043982,  0.03813756],
        [-0.29097867, -0.10147558],
        [ 0.23617756, -0.17476208]],

       [[ 0.08508469, -0.36854734],
        [ 0.24992265,  0.09842862],
        [ 0.59673338,  0.80745527]]])

In [32]:
np.divide(a1,a2)

array([[[ 1.35346872,  1.21955761],
        [ 0.28712959,  0.76271224],
        [ 1.77074133,  0.69295037]],

       [[23.37488778,  0.33084545],
        [ 9.45988721,  1.12118887],
        [ 2.51521272,  8.09572449]]])

In [33]:
np.multiply(a1,a2)

array([[[2.13661760e-01, 3.67968842e-02],
        [4.78386687e-02, 1.39486796e-01],
        [1.66270455e-01, 2.24480907e-01]],

       [[3.38010882e-04, 1.00359581e-01],
        [8.25596900e-03, 7.39598640e-01],
        [3.90110977e-01, 1.04833280e-01]]])

In [34]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2, 8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

## Statistical operations

In [35]:
sqrt

np.float64(5.0)

In [36]:
abs

np.int64(2)

In [37]:
power

np.int64(256)

In [38]:
log

np.float64(3.2188758248682006)

In [39]:
mins

np.float64(0.08888738065266966)

In [40]:
maxs

np.float64(0.8121919177501311)

## Update

In [41]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

### Update

In [42]:
arr3[0][0][2] = 500
arr3

array([[[  1,   4, 500],
        [  6,   7,   4]],

       [[  3,   5,   4],
        [  5,   8,   7]],

       [[  1,   4,   5],
        [  6,   7,   4]]])

In [43]:
# Reshape

In [44]:
arr3.shape

(3, 2, 3)

In [45]:
arr3_reshape = arr3.reshape((2,3,3))
arr3_reshape

array([[[  1,   4, 500],
        [  6,   7,   4],
        [  3,   5,   4]],

       [[  5,   8,   7],
        [  1,   4,   5],
        [  6,   7,   4]]])

### Appending and inserting 

In [49]:
arr3_reshape.shape

(2, 3, 3)

In [50]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

### Create a new Array

In [52]:
new_array= np.ones((3,2,3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [53]:
appd= np.append(zeroes, new_array, axis=0) #axis 0 = row, axis 1 = column
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [56]:
inserted_array= np.insert(zeroes, 1, new_array, axis=0)
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [57]:
arr4= np.random.rand(3,2,3)
arr4

array([[[0.00181129, 0.53353415, 0.43705807],
        [0.20063723, 0.20047432, 0.15385421]],

       [[0.63702201, 0.97965772, 0.12688918],
        [0.57110963, 0.71322763, 0.09717365]],

       [[0.28457733, 0.98241378, 0.87730783],
        [0.74376859, 0.99975422, 0.52666431]]])

In [59]:
arr5= np.delete(arr4, 0, axis=1)

In [60]:
arr5

array([[[0.20063723, 0.20047432, 0.15385421]],

       [[0.57110963, 0.71322763, 0.09717365]],

       [[0.74376859, 0.99975422, 0.52666431]]])

In [63]:
np.save("new_array5", arr5)

In [64]:
np.load("new_array5.npy")

array([[[0.20063723, 0.20047432, 0.15385421]],

       [[0.57110963, 0.71322763, 0.09717365]],

       [[0.74376859, 0.99975422, 0.52666431]]])